### ISSUE TITLE
sitemap generation slowed down on initial request

### ISSUE THREAD

**Issue by joernroeder** [omz13/kirby3-xmlsitemap#27] opened 2019-04-01 10:39 UTC
Hey,
i've just noticed that my build setup (which relies on the sitemap) time slowed down and sometimes broke due to http timeout errors. after digging a bit deeper i've seen the following comment at the end of `sitemap.xml`. Is there anything that changed significantly when iterating through the page tree?

```
<!-- Sitemap generated using https://github.com/omz13/kirby3-xmlsitemap -->
<!-- v1.1.6 -->
<!-- Generation took 191120.47290802 microseconds -->
<!-- Generated at 2019-04-01T10:08:46+00:00 -->
```

**Comment by omz13** [comment] 2019-04-01 12:10
Hi,

That is slow :-( Too slow :-(

There have been no significant changes over the past few releases with my plugin; just minor incremental things. The basic processing loop is essentially the same - iterate over a `Pages` object, descending into children if applicable.

I just ran some tests... something changed (@bastianallgeier) in kirby 3.1:

kirby 3.0.3 time = 211  👍 
kirby 3.1.0 time = 1800  👎

**Comment by bastianallgeier** [comment] 2019-04-01 12:11
Ugh :( Could you create an issue in our repo. We have to check where this comes from.

**Comment by joernroeder** [comment] 2019-04-01 13:04
@omz13 thanks for the fast response and @bastianallgeier thanks for looking into this!

**Comment by omz13** [comment] 2019-04-13 14:07
Root cause fixed in https://github.com/getkirby/kirby/pull/1676

**Closed as completed** 2019-04-13 17:50 UTC
